[build]
builder = "NIXPACKS"

[build.nixpacksPlan.phases.setup]
nixPkgs = ["python310", "python310Packages.pip", "gcc"]

[build.nixpacksPlan.phases.install]
cmds = ["python -m pip install -r requirements.txt"]

[deploy]
startCommand = "python -m uvicorn main:app --host 0.0.0.0 --port ${PORT:-8000}"
