[build]
builder = "NIXPACKS"

[build.nixpacksPlan.phases.setup]
nixPkgs = ["python310", "gcc"]

[build.nixpacksPlan.phases.install]
cmds = ["pip install -r requirements.txt"]

[deploy]
startCommand = "uvicorn main:app --host 0.0.0.0 --port ${PORT:-8000}"
